#!/bin/sh

set -e
set -o pipefail

if [ -z "$1" ]; then
    echo "input file required"
    exit 1
fi

outdir="output"
outfile="$outdir/$RANDOM.png"
mkdir -p "$outdir"

./markovangelo.py $1 > $outfile
open $outfile

echo "$outfile"
