#!/bin/sh

set -e
set -o pipefail

if [ -z "$1" ]; then
    echo "input file required"
    exit 1
fi

outdir="output"
outfile="$outdir/$RANDOM.png"
mkdir -p "$outdir"

./markovangelo.py -n 8 --show --width 800 --height 300 $* > $outfile

echo "$outfile"
